### Iniciar session
POST https://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "me",
  "password": "password"
}

### Obtener mensajes
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTM3YzlkN2I3OWIzNTRiYWM4YTIyNSIsInVzZXJuYW1lIjoibWUiLCJyb2xlIjoiYWRtaW4iLCJuYW1lIjoiSm9zZSBDYXJsb3MiLCJpYXQiOjE3NTUxMDA4NzEsImV4cCI6MTc1NTEwMTc3MX0.GEGzCtkv5XWxv2GChthT7kqxyPYajatPJPZ3wDclAM4
GET https://localhost:3000/api/messages?limit=50
Authorization: Bearer {{accessToken}}


### Query Params
GET https://localhost:3000/api/messages?limit=3&beforeId=689ba9ed9da93223310c1933
Authorization: Bearer {{accessToken}}
