### Iniciar session
POST https://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### Obtener mensajes
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTM3YzlkN2I3OWIzNTRiYWM4YTIyNSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJuYW1lIjoiSm9zZSBDYXJsb3MiLCJpYXQiOjE3NTQ1ODUwMDgsImV4cCI6MTc1NDU4NTkwOH0.ptjZJ6ZUVE3l3MZFxo2Ro9FmzpV0-dEggr-oaX73o-U
GET https://localhost:3000/api/messages?limit=50
Authorization: Bearer {{accessToken}}


### Query Params
GET https://localhost:3000/api/messages?limit=5&offset=0
Authorization: Bearer {{accessToken}}
